name: Tests

on: [push, pull_request]

jobs:
  test:
    name: "Test on Redis ${{ matrix.redis-version }}, Ruby ${{ matrix.ruby-version }}"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        redis-version:
          - '4.0'
          - 4.1
          - 4.2
          - 4.3
          - 4.4
          - 4.5
          - 4.6
          - latest
        ruby-version:
          - head
          - '3.2'
          - '3.1'
          - '3.0'
          - '2.7'
          - '2.6'
          - '2.5'
          - '2.4'
          - jruby-9.3
          - jruby-9.2

    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    env:
      REDIS_VERSION: "${{ matrix.redis-version }}"

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # 'bundle install' and cache

    - name: Run tests
      run: bundle exec rake
